services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://user:password@db:5432/rotaguard
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rotaguard
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
