services:
  web:
    build: .
    ports:
      - "5000:5000"
      - 5678:5678
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://rotaguard:rotapassword@db:5432/rotaguard
      - PYTHONPATH=/usr/src/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - web

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=rotaguard
      - POSTGRES_PASSWORD=rotapassword
      - POSTGRES_DB=rotaguard
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
