"""Implement UserRole association object for audit trail

Revision ID: 08e942fbcaf6
Revises: dfaae2289fb2
Create Date: 2025-09-10 00:10:56.634660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e942fbcaf6'
down_revision = 'dfaae2289fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('human_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_updated_by_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_roles_human_id'), ['human_id'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['last_updated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_roles_human_id'))
        batch_op.drop_column('last_updated_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('human_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
