"""Add user profile fields with defaults

Revision ID: d82ce2ef0a0a
Revises: 9ef4c60204e3
Create Date: 2025-09-29 22:11:47.569798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82ce2ef0a0a'
down_revision = '9ef4c60204e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('address_line_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_line_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('town', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_country_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('twitter_x', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('other_social_media', sa.String(length=255), nullable=True))

    # Update existing users with default values for required fields
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE users 
        SET 
            title = 'Mr',
            address_line_1 = 'To be provided',
            town = 'To be provided',
            county = 'To be provided',
            country = 'United Kingdom',
            phone_country_code = '+44',
            phone_number = 'To be provided'
        WHERE title IS NULL
    """))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('other_social_media')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('twitter_x')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('phone_country_code')
        batch_op.drop_column('country')
        batch_op.drop_column('county')
        batch_op.drop_column('town')
        batch_op.drop_column('address_line_3')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('address_line_1')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
