"""Implement many-to-many relationship for user roles

Revision ID: dfaae2289fb2
Revises: 7e5f50430408
Create Date: 2025-09-09 23:23:53.006479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfaae2289fb2'
down_revision = '7e5f50430408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint(batch_op.f('roles_manager_id_fkey'), type_='foreignkey')
        batch_op.drop_column('manager_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_role_id'), type_='foreignkey')
        batch_op.drop_column('role_id')
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_role_id'), 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('roles_manager_id_fkey'), 'users', ['manager_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('user_roles')
    # ### end Alembic commands ###
